id: P001813
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS19969
  title: བདེ་བ་ཅན་དུ་བགྲོད་པའི་ཆོ་ག་དཔག་མེད་མྱུར་ལམ་དང་འབྲེལ་བའི་ཚེ་སྒྲུབ་ཀྱི་གདམས་པ་སྙིང་པོར་དྲིལ་བ།
  author: ''
  volumes:
    9c31e9104b7c480d8bf38faca2fdfa24:
      image_group_id: I8LS19971
      title: ''
      volume_number: 1
      total_pages: 22
      base_file: v001.txt
