id: P001813
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19969
  title: བདེ་བ་ཅན་དུ་བགྲོད་པའི་ཆོ་ག་དཔག་མེད་མྱུར་ལམ་དང་འབྲེལ་བའི་ཚེ་སྒྲུབ་ཀྱི་གདམས་པ་སྙིང་པོར་དྲིལ་བ།
  author: ''
  volumes: {}
